//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/Quest64.z64", "rom/Quest64.mod.z64", 0 // Open the ROM file
.headersize 0x7FFFF400
.org 0x80410000
.importobj "obj/main.o"
.include "asm/Quest64.asm"
.include "asm/boot.asm"
.include "asm/dataPatches.asm"
.include "asm/symbols.asm"
.close //close file
