//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/Quest64.z64", "rom/Quest64.mod.z64", 0 // Open the ROM file
.include "asm/Quest64.asm" // Include Quest64.asm to tell armips' linker where to find the game's function(s)
.headersize 0x7FFFF400
.org 0x80410000
.include "asm/boot.asm"
.importobj "obj/main.o"
.close //close file
