import os
import re
import subprocess

# Define the directory path
directory_path = 'img/'
image_bin_path = 'asm/!image_bin.s'
img_converter_path = 'tools/image_converter.py'

with open(image_bin_path, 'w') as file:
    file.write("//Generated by convert_images.py\n")

if not os.path.exists("obj/"):
    os.makedirs("obj/")
if not os.path.exists("obj/img/"):
    os.makedirs("obj/img/")

#.\tools\image_converter.py ci8 .\img\Qutest.DAC040.ci8-export.png obj/title_screen.png

# Iterate through files in the directory
with open(image_bin_path, 'a') as file:
    for file_name in os.listdir(directory_path):
        if file_name.endswith('.png'):
            # Try to extract a hexadecimal name and file type using regex
            match = re.match(r'([A-F0-9]+)_(?:[^_]+)\.(\w+)\.png', file_name)

            if match:
                # If a hexadecimal name is found, use it
                hex_name = match.group(1)
                file_type = match.group(2)
                print(f"File: {file_name}\nHexadecimal Name: {hex_name}\nFile Type: {file_type}\n")
                file.write(f".org 0x{hex_name}\n\t.incbin \"obj/{directory_path}{file_name[:-4] + '.bin'}\"\n")
                out_file_path = f"obj/{directory_path}{file_name}"
                out_file_path = out_file_path[:-4] + '.bin'
                if file_type == "pal":
                    file_type = "palette"
                command = [
                    "python",
                    f"{img_converter_path}",
                    f"{file_type}",
                    f"{directory_path}{file_name}",
                    f"{out_file_path}"
                ]
                #print(command)
                subprocess.call(command)
            else:
                # If no hexadecimal name is found, use everything until the first dot as the name
                name_match = re.match(r'([^\.]+)\.\w+\.png', file_name)
                if name_match:
                    hex_name = name_match.group(1)
                    file_type = "Unknown"  # You can set a default value for file type
                print(f"File: {file_name}\nFile Type: {file_type}\n")

