#!/usr/bin/env python3
import sys
from pathlib import Path

def main():
    if len(sys.argv) < 5:
        print("Usage: generate_main.py <output_file> <rom_in> <rom_out> <headersize_expr> "
              "<sources_before_headersize...> -- <sources_asm...> -- <objects...>")
        sys.exit(1)

    output_file = Path(sys.argv[1])
    rom_in = Path(sys.argv[2])
    rom_out = sys.argv[3]
    headersize_expr = sys.argv[4]

    # --- NEW: Error if input ROM not found ---
    if not rom_in.exists():
        print(f"Error: Input ROM file not found: {rom_in}")
        sys.exit(1)

    # Split argument groups by "--"
    try:
        idx1 = sys.argv.index("--", 5)
        idx2 = sys.argv.index("--", idx1 + 1)
    except ValueError:
        print("Error: Missing argument separators '--'")
        sys.exit(1)

    sources_before = sys.argv[5:idx1]
    sources_asm = sys.argv[idx1 + 1:idx2]
    objects = sys.argv[idx2 + 1:]

    # Write output
    with output_file.open("w", encoding="utf-8") as f:
        f.write("//Automatically generated by python script, do not edit\n")
        f.write(".n64 // Let armips know we're coding for the N64 architecture\n")
        f.write(f'.open "{rom_in}", "{rom_out}", 0 // Open the ROM file\n')

        for src in sources_before:
            f.write(f'.include "{src}"\n')

        f.write(f".headersize {headersize_expr}\n")
        f.write(".org 0x800c0000\n")

        for src in sources_asm:
            f.write(f'.include "{src}"\n')

        for obj in objects:
            f.write(f'.importobj "{obj}"\n')

        f.write(".close //close file\n")

if __name__ == "__main__":
    main()
